name: RushShop
version: '${project.version}'
main: com.blocky.dev.rushshop.RushShop
api-version: 1.13
authors: [BlockyDev]
depend: [Vault]
commands:
    auctionhouse:
        description: Access the auction house and it's functionalities.
        permission: rushshop.command.ah
        aliases: [ah]
        default: true